#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to that shell before running this script.
#       e.g. SHELL=/usr/bin/ksh ./gradlew
#
#   (2) The Java installation used by this script is determined by the
#       JAVA_HOME environment variable. If Java is not installed, or if
#       JAVA_HOME is not set, then fallback to detecting Java via the
#       "java" command, which must be in the PATH of the current process.
#
##############################################################################

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# Some standard non-POSIX shells will fail on ulimit -n. First try the
# POSIX-compliant way, then fallback to the standard sh way.
ulimit -n "$MAX_FD" 2> /dev/null || {
  ulimit -n 1024 2> /dev/null
  test $? -eq 0 || ulimit -n 65536 2> /dev/null
} || {
  echo >&2 "warning: could not set file descriptor limit, using default"
}

# Set to the actual Gradle version
GRADLE_VERSION="8.0"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$(uname)" = "Darwin" ] && [ "$(uname -m)" = "arm64" ]; then
  # macOS ARM64 uses a different Java home path
  if [ -z "$JAVA_HOME" ]; then
    JAVA_HOME=$(/usr/libexec/java_home)
  fi
fi

# Determine if Gradle is a script or a binary
if [ -f "$GRADLE_HOME/bin/gradle" ]; then
    GRADLE_CMD="$GRADLE_HOME/bin/gradle"
else
    GRADLE_CMD=gradle
fi

# Export GRADLE_OPTS
GRADLE_OPTS="$GRADLE_OPTS -Xmx2048m"

# Run Gradle
exec "$JAVACMD" $GRADLE_OPTS -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
